import React, { useEffect, useState } from 'react';
import { RefreshCw, Shield, UserRound } from 'lucide-react';
import { base44 } from '@/api/base44Client';
import { Button } from '@/components/ui/button';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Image } from '@/components/ui/image';
import SeasonCompetitionCard from '@/components/agency/player-tabs/SeasonCompetitionCard';
import PlayerMatchStatsTable from '@/components/agency/player-tabs/PlayerMatchStatsTable';

export default function ApiFootballStatsPanel({ player }) {
  const [season, setSeason] = useState('2026'), [seasonStats, setSeasonStats] = useState([]), [matchStats, setMatchStats] = useState([]), [fixtures, setFixtures] = useState([]), [syncingSeason, setSyncingSeason] = useState(false), [syncingFixture, setSyncingFixture] = useState(''), [notice, setNotice] = useState('');
  const loadData = async () => { const [stats, fixtureRows, savedSeasonStats] = await Promise.all([base44.entities.PlayerMatchStats.filter({ organization_id: player.organization_id, player_id: player.id }, '-match_date', 100), base44.entities.ClubFixture.filter({ organization_id: player.organization_id }, '-fixture_date', 100), base44.entities.PlayerSeasonStats.filter({ organization_id: player.organization_id, player_id: player.id, season }, '-updated_date', 50)]); setMatchStats(stats); setFixtures(fixtureRows); setSeasonStats(savedSeasonStats.map(item => item.extra_stats).filter(Boolean)); };
  useEffect(() => { loadData(); }, [player.id, season]);
  const syncSeason = async () => { setSyncingSeason(true); setNotice(''); try { const response = await base44.functions.invoke('syncPlayerStats', { player_id: player.id, season: Number(season) }); setSeasonStats(response.data.season_stats?.competitions || []); setNotice(response.data.message || 'Estadísticas de temporada actualizadas.'); } catch (error) { setNotice(error.response?.data?.error || 'No fue posible sincronizar las estadísticas.'); } setSyncingSeason(false); };
  const syncFixture = async fixture => { setSyncingFixture(fixture.id); try { await base44.functions.invoke('syncMatchStats', { fixture_id: fixture.provider_fixture_id, organization_id: player.organization_id }); await loadData(); } finally { setSyncingFixture(''); } };
  return <div className="space-y-5"><div className="rounded-xl bg-slate-900 p-4 text-white"><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-center gap-3"><div className="h-12 w-12 overflow-hidden rounded-full bg-slate-700">{player.photo_url ? <Image src={player.photo_url} alt={`${player.first_name} ${player.last_name}`} className="h-full w-full" /> : <UserRound className="m-3 h-6 w-6 text-slate-300" />}</div><div><p className="font-semibold">Ficha física</p><p className="text-xs text-slate-300">{player.nationality || 'Nacionalidad —'} · {player.height ? `${player.height} cm` : 'Altura —'} · {player.weight ? `${player.weight} kg` : 'Peso —'}</p></div></div><div className="flex gap-2"><Select value={season} onValueChange={setSeason}><SelectTrigger className="w-24 border-slate-600 bg-slate-800 text-white"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="2026">2026</SelectItem><SelectItem value="2025">2025</SelectItem><SelectItem value="2024">2024</SelectItem></SelectContent></Select><Button size="sm" onClick={syncSeason} disabled={syncingSeason} className="bg-white text-slate-900 hover:bg-slate-100"><RefreshCw className={`mr-1 h-4 w-4 ${syncingSeason ? 'animate-spin' : ''}`} />Sincronizar</Button></div></div></div>{notice && <p className="text-sm text-slate-500">{notice}</p>}<section className="space-y-3"><div className="flex items-center gap-2"><Shield className="h-4 w-4 text-blue-600" /><h2 className="font-semibold text-slate-900">Estadísticas de temporada</h2></div>{seasonStats.length ? seasonStats.map((stats, index) => <SeasonCompetitionCard key={`${stats.league_id}-${index}`} stats={stats} />) : <div className="rounded-xl border border-dashed border-slate-200 py-8 text-center text-sm text-slate-400">Elegí una temporada y sincronizá para consultar las estadísticas oficiales.</div>}</section><section className="space-y-3"><div><h2 className="font-semibold text-slate-900">Estadísticas por partido</h2><p className="text-sm text-slate-500">Los valores se actualizan desde los fixtures de API-Football.</p></div><PlayerMatchStatsTable stats={matchStats} fixtures={fixtures.filter(fixture => (fixture.mapped_club_ids || []).includes(player.current_club_id))} syncingId={syncingFixture} onSync={syncFixture} /></section></div>;
}