import React from 'react';
import { RefreshCw } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { formatDate } from '@/lib/roleUtils';

export default function PlayerMatchStatsTable({ stats, fixtures, syncingId, onSync }) {
  const rows = fixtures.map(fixture => ({ fixture, stat: stats.find(stat => stat.club_fixture_id === fixture.id) })).sort((a, b) => new Date(b.fixture.fixture_date) - new Date(a.fixture.fixture_date));
  if (!rows.length) return <div className="rounded-xl border border-dashed border-slate-200 py-10 text-center text-sm text-slate-400">No hay fixtures asociados al club actual del jugador.</div>;
  return <div className="overflow-x-auto rounded-xl border border-slate-200"><table className="min-w-[1050px] w-full text-xs"><thead className="bg-slate-50 text-slate-500"><tr>{['Fecha', 'Competencia · Rival', 'Min.', 'Rating', 'G/A', 'Tiros', 'Pases', 'Dribles', 'Duelos', 'Faltas', 'Tackles', 'Tarjetas', 'Seguimiento', ''].map(label => <th key={label} className="px-3 py-3 text-left font-medium">{label}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">{rows.map(({ fixture, stat }) => <tr key={fixture.id} className="text-slate-600"><td className="whitespace-nowrap px-3 py-3">{formatDate(fixture.fixture_date)}</td><td className="px-3 py-3"><p className="font-medium text-slate-800">{fixture.competition_name || '—'}</p><p className="text-slate-400">{fixture.home_team_name} vs {fixture.away_team_name}</p></td>{stat ? <><td className="px-3 py-3">{stat.minutes_played || 0}</td><td className="px-3 py-3 font-semibold">{stat.rating ?? '—'}</td><td className="px-3 py-3">{stat.goals || 0} / {stat.assists || 0}</td><td className="px-3 py-3">{stat.shots_total || 0} · {stat.shots_on || 0}</td><td className="px-3 py-3">{stat.passes_total || 0} · {stat.passes_key || 0} · {stat.passes_accuracy || 0}%</td><td className="px-3 py-3">{stat.dribbles_attempts || 0} · {stat.dribbles_success || 0}</td><td className="px-3 py-3">{stat.duels_total || 0} · {stat.duels_won || 0}</td><td className="px-3 py-3">{stat.fouls_committed || 0} · {stat.fouls_drawn || 0}</td><td className="px-3 py-3">{stat.tackles_total || 0} · {stat.tackles_interceptions || 0}</td><td className="px-3 py-3">{stat.yellow_cards || 0}A / {stat.red_cards || 0}R</td><td className="px-3 py-3"><span className={stat.follow_up_status === 'completed' ? 'text-emerald-600' : 'text-amber-600'}>{stat.follow_up_status === 'completed' ? 'Completado' : 'Pendiente'}</span></td></> : <td colSpan="10" className="px-3 py-3 text-center text-slate-400">Sin estadísticas sincronizadas</td>}<td className="px-3 py-3"><Button size="sm" variant="ghost" disabled={syncingId === fixture.id} onClick={() => onSync(fixture)}><RefreshCw className={`h-3.5 w-3.5 ${syncingId === fixture.id ? 'animate-spin' : ''}`} /></Button></td></tr>)}</tbody></table></div>;
}