import React,{useState,useEffect,useRef,useMemo} from 'react';
import { Link } from 'react-router-dom';
import { useQuery,useQueryClient } from '@tanstack/react-query';
import { base44 } from '@/api/base44Client';
import { useAuth } from '@/lib/AuthContext';
import { getUserOrgId,POSITION_LABELS } from '@/lib/roleUtils';
import { Button } from '@/components/ui/button';
import { Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription } from '@/components/ui/dialog';
import { CalendarDays,Trophy,CheckCheck,FileClock,Star,BarChart3,TrendingUp,UserRound,Database,Sparkles,SlidersHorizontal,GripVertical,ArrowUp,ArrowDown,X,Plus,Check,RefreshCw,ArrowUpRight,LockKeyhole,Loader2,LayoutGrid } from 'lucide-react';
import { WIDGET_CATALOG,METRICS,seasonStats,argentinaDay,contractDays,dateLabel,moveWidget } from '@/components/agency/dashboard/personalDashboardModel';
import SportmonksSetup from '@/components/agency/dashboard/SportmonksSetup';

const ICONS={CalendarDays,Trophy,CheckCheck,FileClock,Star,BarChart3,TrendingUp,UserRound,Database,Sparkles};
const ACCENTS={emerald:'#059669',blue:'#2563eb',violet:'#7c3aed'};
const selectClass='max-w-full rounded-lg border border-slate-200 bg-white px-2 py-1.5 text-xs text-slate-700';
const EMPTY_SETTINGS={widgets:[],favorite_player_ids:[],featured_player_id:'',season_id:'',ranking_metric:'minutes',accent:'emerald',compact:false};
function Empty({children,action}) {return <div className="rounded-2xl border border-dashed border-slate-200 bg-slate-50/70 p-6 text-center"><p className="text-sm leading-6 text-slate-500">{children}</p>{action&&<div className="mt-3">{action}</div>}</div>;}
function Portrait({player,large=false}) {return <div className={(large?'h-20 w-20 rounded-2xl':'h-10 w-10 rounded-xl')+' shrink-0 bg-slate-100 relative overflow-hidden flex items-center justify-center text-slate-500 font-bold'}><span>{player?.name?.split(' ').map(x=>x[0]).slice(0,2).join('')||'SF'}</span>{player?.photo_url&&<img className="absolute inset-0 h-full w-full object-cover" src={player.photo_url} alt="" onError={e=>{e.currentTarget.style.display='none';}}/>}</div>;}
function PlayerLine({player,children}) {return <div className="flex items-center gap-3 min-w-0"><Portrait player={player}/><div className="min-w-0 flex-1"><Link to={'/agency/players/'+player.id} className="text-sm font-semibold text-slate-900 hover:underline">{player.name}</Link><p className="text-xs text-slate-400 truncate">{player.club||'Club sin registrar'} · {POSITION_LABELS[player.position]||player.position}</p></div>{children}</div>;}
async function call(name,payload) {const r=await base44.functions.invoke(name,payload);if(!r.data?.success)throw new Error(r.data?.error||'No se pudo completar.');return r.data;}

export default function PersonalDashboard() {
 const {user}=useAuth();const orgId=getUserOrgId(user);
 if(!orgId)return <div className="p-8 text-slate-500">Seleccioná una agencia para abrir tu tablero.</div>;
 return <Workspace key={orgId+':'+user?.id} orgId={orgId} user={user}/>;
}
function Workspace({orgId,user}) {
 const cache=useQueryClient(),initialized=useRef(false),mounted=useRef(true);
 const [settings,setSettings]=useState(null),[revision,setRevision]=useState(0),[editing,setEditing]=useState(false),[catalog,setCatalog]=useState(false),[setup,setSetup]=useState(false),[dirty,setDirty]=useState(false),[saving,setSaving]=useState(false),[message,setMessage]=useState(''),[busy,setBusy]=useState(''),[now,setNow]=useState(new Date());
 const key=['personal-dashboard',orgId,user.id];
 const query=useQuery({queryKey:key,queryFn:()=>call('personal-dashboard',{organization_id:orgId}),staleTime:30000,refetchInterval:60000,retry:1});
 useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;};},[]);
 useEffect(()=>{if(query.data&&!initialized.current){setSettings(query.data.settings);setRevision(query.data.revision);initialized.current=true;}},[query.data]);
 useEffect(()=>{const timer=setInterval(()=>setNow(new Date()),30000);return()=>clearInterval(timer);},[]);
 useEffect(()=>{if(!dirty)return;const before=e=>{e.preventDefault();e.returnValue='';};window.addEventListener('beforeunload',before);return()=>window.removeEventListener('beforeunload',before);},[dirty]);
 const data=query.data;
 const prefs=settings||EMPTY_SETTINGS;
 const change=patch=>{setSettings(current=>({...current,...patch}));setDirty(true);setMessage('');};
 const refresh=()=>cache.invalidateQueries({queryKey:key});
 const fail=e=>e.response?.data?.error||e.message||'No se pudo completar.';
 const save=async()=>{
  setSaving(true);setMessage('');
  try {const result=await call('personal-dashboard',{organization_id:orgId,action:'save',revision,settings:prefs});
   if(!mounted.current)return;
   setSettings(result.settings);setRevision(result.revision);setDirty(false);setEditing(false);setMessage('Tu tablero quedó guardado.');await refresh();
  }catch(e){if(mounted.current)setMessage(fail(e));}finally{if(mounted.current)setSaving(false);}
 };
 const resetDraft=()=>{setSettings(data.settings);setRevision(data.revision);setDirty(false);setEditing(false);setMessage('Cambios descartados.');};
 const patchWidget=(id,patch)=>change({widgets:prefs.widgets.map(w=>w.id===id?{...w,...patch}:w)});
 const toggleWidget=id=>change({widgets:prefs.widgets.some(w=>w.id===id)?prefs.widgets.filter(w=>w.id!==id):[...prefs.widgets,{id,size:['fixtures','ranking'].includes(id)?'wide':'normal',limit:5}]});
 const toggleFavorite=id=>change({favorite_player_ids:prefs.favorite_player_ids.includes(id)?prefs.favorite_player_ids.filter(x=>x!==id):[...prefs.favorite_player_ids,id].slice(0,50)});
 const shift=(id,step)=>{const index=prefs.widgets.findIndex(w=>w.id===id),target=prefs.widgets[index+step];if(target)change({widgets:moveWidget(prefs.widgets,id,target.id)});};
 const complete=async eventId=>{setBusy(eventId);setMessage('');try{await call('agency-intelligence',{organization_id:orgId,action:'complete_task',event_id:eventId});await refresh();}catch(e){setMessage(fail(e));}finally{setBusy('');}};
 const sync=async playerId=>{setBusy(playerId);setMessage('');try{const r=await call('sportmonks-player',{organization_id:orgId,action:'sync',player_id:playerId});setMessage(r.message);await refresh();}catch(e){setMessage(fail(e));}finally{setBusy('');}};
 const seasons=useMemo(()=>[...new Map((data?.sportmonks.snapshots||[]).flatMap(s=>s.seasons).map(s=>[s.season_id,{id:s.season_id,name:(s.league_name?s.league_name+' · ':'')+s.season_name,start:s.season_start||''}])).values()].sort((a,b)=>b.start.localeCompare(a.start)||b.id.localeCompare(a.id)),[data]);
 const seasonId=seasons.some(s=>s.id===prefs.season_id)?prefs.season_id:seasons[0]?.id||'';
 const seasonName=seasons.find(s=>s.id===seasonId)?.name||'Temporada pendiente';
 const snapshots=new Map((data?.sportmonks.snapshots||[]).map(s=>[s.player_id,s]));
 const statPlayers=(data?.players||[]).map(p=>({...p,...seasonStats(snapshots.get(p.id)?.seasons||[],seasonId),synced_at:snapshots.get(p.id)?.synced_at}));
 const today=argentinaDay(now);
 const pending=(data?.events||[]).filter(e=>e.event_type==='follow_up'&&['scheduled','confirmed'].includes(e.status));
 const overdue=pending.filter(e=>Date.parse(e.start_date)<now.getTime());
 const contracts=(data?.players||[]).map(p=>({...p,days:contractDays(p.contract_end,now)})).filter(p=>p.days!==null&&p.days<=180).sort((a,b)=>a.days-b.days);
 const permitted=w=>{const meta=WIDGET_CATALOG.find(c=>c.id===w.id);return meta&&(!meta.permission||data?.permissions[meta.permission]);};
 const visible=prefs.widgets.filter(permitted);
 const accent=ACCENTS[prefs.accent]||ACCENTS.emerald;
 const ranked=[...statPlayers].filter(p=>p[prefs.ranking_metric]!==null).sort((a,b)=>b[prefs.ranking_metric]-a[prefs.ranking_metric]);
 const focus=statPlayers.find(p=>p.id===prefs.featured_player_id)||statPlayers.find(p=>prefs.favorite_player_ids.includes(p.id))||statPlayers[0];
 const selectedSource=<span className="text-[10px] text-slate-400">Sportmonks · {seasonName}</span>;

 if(query.isPending||(!settings&&!query.isError))return <div className="p-6 md:p-8 space-y-5 animate-pulse"><div className="h-56 rounded-3xl bg-slate-200"/><div className="grid md:grid-cols-3 gap-5">{[1,2,3,4,5,6].map(i=><div key={i} className="h-64 bg-slate-100 rounded-2xl"/>)}</div></div>;
 if(query.isError&&!data)return <div className="p-8"><h1 className="text-2xl font-bold">Mi tablero</h1><p className="my-4 text-rose-700">{fail(query.error)}</p><Button onClick={()=>query.refetch()}>Reintentar</Button></div>;

 const body=(widget)=>{
  const limit=widget.limit;
  if(widget.id==='agenda') {
   const events=data.events.filter(e=>argentinaDay(e.start_date)===today).sort((a,b)=>a.start_date.localeCompare(b.start_date));
   return <><p className="text-xs text-slate-400 mb-4">HOY · HORA ARGENTINA</p>{events.length?<div className="space-y-4">{events.slice(0,limit).map(e=>{const passed=Date.parse(e.end_date||e.start_date)<now.getTime(),done=e.status==='completed';return <div key={e.id} className="flex gap-3"><div className={'mt-1 h-2 w-2 rounded-full '+(done?'bg-emerald-500':passed?'bg-amber-400':'bg-slate-300')}/><div className="flex-1"><p className={'text-sm font-medium '+(done?'line-through text-slate-400':'text-slate-800')}>{e.title}</p><p className="text-xs text-slate-400 mt-1">{dateLabel(e.start_date)} {done?'· Completado':passed?'· Horario transcurrido':''}</p></div></div>;})}</div>:<Empty>Tu agenda está libre para hoy.</Empty>}<Link to="/agency/calendar" className="mt-5 text-xs font-semibold inline-flex items-center gap-1" style={{color:accent}}>Organizar mi agenda<ArrowUpRight size={13}/></Link></>;
  }
  if(widget.id==='fixtures') {
   const fixtures=data.fixtures.filter(f=>!['FT','AET','PEN','CANC','ABD','AWD','WO','POSTP'].includes(f.status)).sort((a,b)=>String(a.date).localeCompare(String(b.date)));
   return <>{fixtures.length?<div className="space-y-3">{fixtures.slice(0,limit).map(f=><div key={f.id} className="border border-slate-100 rounded-2xl p-4"><div className="flex justify-between gap-2 text-[10px] uppercase tracking-wide text-slate-400"><span>{f.competition||'Competencia sin registrar'}</span><span>{['1H','2H','HT','ET','LIVE'].includes(f.status)?'EN JUEGO':dateLabel(f.date)}</span></div><div className="flex items-center justify-between gap-2 my-3"><div className="flex items-center gap-2 text-sm font-semibold">{f.home_logo&&<img src={f.home_logo} alt="" className="h-7 w-7 object-contain"/>}{f.home}</div><span className="text-xs text-slate-400 shrink-0">{f.home_score!=null&&f.away_score!=null?f.home_score+' - '+f.away_score:'VS'}</span><div className="flex items-center gap-2 text-sm font-semibold text-right">{f.away}{f.away_logo&&<img src={f.away_logo} alt="" className="h-7 w-7 object-contain"/>}</div></div><p className="text-xs text-slate-500">{f.players.map(p=>p.name).join(' · ')}</p><p className="text-[10px] text-slate-400 mt-2">Fuente: {f.provider==='api_football'?'API-Football':f.provider==='sportmonks'?'Sportmonks':f.provider||'Registro manual'} · Último registro: {dateLabel(f.synced_at)}</p></div>)}</div>:<Empty>No hay próximos partidos vinculados a tu cartera en los registros de los próximos 14 días.</Empty>}<Link to="/agency/operations" className="inline-flex gap-1 mt-4 text-xs font-semibold" style={{color:accent}}>Ver agenda y partidos<ArrowUpRight size={13}/></Link></>;
  }
  if(widget.id==='tasks')return <>{pending.length?<div className="space-y-4">{pending.slice(0,limit).map(e=><div key={e.id} className="flex items-start gap-3"><button onClick={()=>complete(e.id)} disabled={!!busy} aria-label={'Completar '+e.title} className="mt-0.5 h-6 w-6 rounded-lg border border-slate-200 flex items-center justify-center hover:bg-emerald-50"><Check size={13}/></button><div className="flex-1"><p className="text-sm font-medium">{e.title}</p><p className="text-xs text-slate-400 mt-1">{e.player_name||'Seguimiento'} · {dateLabel(e.start_date)}</p>{Date.parse(e.start_date)<now.getTime()&&<span className="text-[10px] text-rose-600">FECHA PASADA · REQUIERE REVISIÓN</span>}</div></div>)}</div>:<Empty>No hay seguimientos pendientes en los registros de los últimos 90 días.</Empty>}<Link to="/agency/intelligence" className="inline-flex gap-1 text-xs font-semibold mt-5" style={{color:accent}}>Programar un seguimiento<ArrowUpRight size={13}/></Link></>;
  if(widget.id==='contracts')return <>{contracts.length?<div className="space-y-4">{contracts.slice(0,limit).map(p=><div key={p.id}><PlayerLine player={p}><span className={'shrink-0 rounded-lg px-2 py-1 text-xs font-bold '+(p.days<=30?'bg-rose-50 text-rose-700':'bg-amber-50 text-amber-700')}>{p.days<0?'Revisar':p.days+' días'}</span></PlayerLine><p className="text-[10px] text-slate-400 mt-2 ml-[52px]">{dateLabel(p.contract_end,false)} · {p.days<0?'Fecha registrada pasada; confirmar situación':'Vencimiento registrado'}</p></div>)}</div>:<Empty>No hay vencimientos registrados dentro de 180 días.</Empty>}<p className="text-[10px] mt-5 text-slate-400">Una fecha faltante o pasada no acredita que el jugador esté libre.</p></>;
  if(widget.id==='favorites') {const favorites=data.players.filter(p=>prefs.favorite_player_ids.includes(p.id));return <>{favorites.length?<div className="space-y-4">{favorites.slice(0,limit).map(p=><PlayerLine key={p.id} player={p}><Star className="h-4 w-4 fill-amber-400 text-amber-400"/></PlayerLine>)}</div>:<Empty action={<button className="text-xs font-semibold" style={{color:accent}} onClick={()=>setCatalog(true)}>Elegir jugadores</button>}>Marcá a los jugadores que querés tener siempre a mano.</Empty>}<button className="mt-4 text-xs text-slate-500 hover:text-slate-900" onClick={()=>setCatalog(true)}>Editar mi selección personal</button></>;}
  if(widget.id==='ranking')return <><div className="flex flex-wrap gap-2 justify-between items-center mb-5"><select aria-label="Métrica del ranking" className={selectClass} value={prefs.ranking_metric} onChange={e=>change({ranking_metric:e.target.value})}>{Object.entries(METRICS).map(([id,label])=><option key={id} value={id}>{label}</option>)}</select>{selectedSource}</div>{ranked.length?<div className="space-y-4">{ranked.slice(0,limit).map((p,i)=><div key={p.id}><div className="flex items-center gap-3"><span className="text-xs text-slate-300 w-4">{String(i+1).padStart(2,'0')}</span><div className="flex-1"><PlayerLine player={p}><strong className="text-xl tabular-nums">{p[prefs.ranking_metric].toLocaleString('es-AR')}</strong></PlayerLine></div></div><div className="h-1.5 rounded-full bg-slate-100 ml-7 mt-2 overflow-hidden"><div style={{width:((p[prefs.ranking_metric]/Math.max(ranked[0][prefs.ranking_metric],1))*100)+'%',backgroundColor:accent}} className="h-full rounded-full transition-all duration-500"/></div></div>)}</div>:<Empty>Las estadísticas de esta temporada aparecerán al sincronizar Sportmonks. No hay valores disponibles para esta métrica.</Empty>}<p className="text-[10px] text-slate-400 mt-4">Comparación de registros en la misma temporada/competición, sin mezclar proveedores.</p></>;
  if(widget.id==='contributions') {const rows=statPlayers.filter(p=>p.goals!==null&&p.assists!==null).sort((a,b)=>(b.goals+b.assists)-(a.goals+a.assists)).slice(0,limit),max=Math.max(1,...rows.map(p=>p.goals+p.assists));return <>{selectedSource}<div className="flex gap-4 text-[10px] text-slate-500 my-4"><span>● Goles</span><span className="text-sky-500">● Asistencias</span></div>{rows.length?<div className="space-y-5">{rows.map(p=><div key={p.id}><div className="flex justify-between text-xs mb-2"><Link to={'/agency/players/'+p.id} className="font-medium hover:underline">{p.name}</Link><span>{p.goals} G · {p.assists} A</span></div><div className="h-3 rounded-full bg-slate-100 flex overflow-hidden"><div style={{width:p.goals/max*100+'%',backgroundColor:accent}}/><div className="bg-sky-400" style={{width:p.assists/max*100+'%'}}/></div></div>)}</div>:<Empty>Sin goles y asistencias informados para esta temporada.</Empty>}</>;}
  if(widget.id==='spotlight')return focus?<><select className={selectClass+' w-full mb-5'} aria-label="Jugador destacado" value={focus.id} onChange={e=>change({featured_player_id:e.target.value})}>{data.players.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select><div className="flex items-center gap-4"><Portrait large player={focus}/><div><h3 className="font-bold text-lg">{focus.name}</h3><p className="text-xs text-slate-500 mt-1">{focus.club||'Club sin registrar'}</p><p className="text-xs mt-1" style={{color:accent}}>{POSITION_LABELS[focus.position]||focus.position}</p></div></div>{data.permissions.statistics&&<><div className="grid grid-cols-3 gap-2 mt-5">{[['minutes','Minutos'],['goals','Goles'],['assists','Asistencias']].map(([k,label])=><div key={k} className="rounded-xl bg-slate-50 p-3 text-center"><p className="text-xl font-bold">{focus[k]??'—'}</p><p className="text-[10px] text-slate-400">{label}</p></div>)}</div><div className="mt-3">{selectedSource}</div><p className="text-[10px] text-slate-400 mt-1">Última consulta: {dateLabel(focus.synced_at)}</p><Button variant="outline" size="sm" className="mt-4 w-full" disabled={!!busy||!data.sportmonks.configured} onClick={()=>sync(focus.id)}><RefreshCw size={13} className={'mr-2 '+(busy===focus.id?'animate-spin':'')}/>Actualizar Sportmonks</Button></>}<Link to={'/agency/players/'+focus.id} className="text-xs font-semibold inline-flex mt-4 gap-1" style={{color:accent}}>Ver ficha completa<ArrowUpRight size={13}/></Link></>:<Empty>No hay jugadores asignados a tu usuario.</Empty>;
  if(widget.id==='coverage') {const withStats=statPlayers.filter(p=>p.records>0).length,stale=data.sportmonks.snapshots.filter(s=>Date.parse(s.synced_at)<now.getTime()-86400000).length;return <><div className="flex items-end gap-2"><strong className="text-4xl tracking-tight">{withStats}</strong><span className="text-sm text-slate-400 mb-1">/ {data.players.length} jugadores</span></div><p className="text-xs text-slate-500 mt-2">Con registros en la temporada seleccionada</p><div className="h-2 rounded-full bg-slate-100 mt-4 overflow-hidden"><div className="h-full rounded-full" style={{width:(withStats/Math.max(data.players.length,1)*100)+'%',backgroundColor:accent}}/></div><div className="mt-5 space-y-3 text-sm"><div className="flex justify-between"><span className="text-slate-500">Identidades vinculadas</span><strong>{data.sportmonks.linked_players}</strong></div><div className="flex justify-between"><span className="text-slate-500">Consultas de más de 24 h</span><strong>{stale}</strong></div><div className="flex justify-between"><span className="text-slate-500">Credencial</span><span>{data.sportmonks.configured?'Configurada':'Pendiente'}</span></div></div><button className="text-xs font-semibold mt-5" style={{color:accent}} onClick={()=>setSetup(true)}>Revisar conexión y perfiles</button></>;}
  if(widget.id==='assistant')return <div className="rounded-2xl p-5 text-white bg-slate-900"><Sparkles size={24} className="text-emerald-300"/><h3 className="font-semibold mt-4 text-lg">Llegá a cada reunión con contexto.</h3><p className="text-sm text-slate-300 mt-2 leading-6">Prepará preguntas, revisá datos faltantes y definí la próxima acción con el asistente de Score.</p><Link className="inline-flex items-center gap-2 mt-5 text-xs font-semibold text-emerald-300" to="/agency/intelligence">Abrir seguimiento y asistente<ArrowUpRight size={14}/></Link><p className="text-[10px] text-slate-400 mt-4">El asistente del Centro de Inteligencia indica sus propias fuentes.</p></div>;
  return null;
 };

 return <div className="min-h-screen bg-[#f3f5f8] p-4 md:p-7 xl:p-9 pb-28">
  <div className="max-w-[1600px] mx-auto space-y-6">
   <header className="relative overflow-hidden rounded-[28px] bg-[#101c32] text-white px-6 py-7 md:px-8">
    <div className="absolute w-80 h-80 -right-10 -top-40 rounded-full blur-3xl opacity-20 pointer-events-none" style={{backgroundColor:accent}}/>
    <div className="relative flex flex-wrap justify-between items-start gap-5">
     <div><div className="text-[10px] font-semibold tracking-[0.25em] uppercase text-slate-400">SCORE FÚTBOL / ESPACIO PERSONAL</div><h1 className="text-3xl md:text-4xl tracking-tight font-bold mt-3">Tu cartera. Tu día.</h1><p className="text-sm text-slate-300 mt-3">Hola, {user.full_name?.split(' ')[0]||'representante'}. Este tablero se adapta a tu forma de trabajar.</p><p className="mt-4 inline-flex items-center gap-1.5 text-xs text-slate-400"><LockKeyhole size={12}/>Diseño personal · {data.scope}</p></div>
     <div className="flex gap-2"><Button variant="outline" className="border-white/20 bg-white/5 text-white hover:bg-white/10 hover:text-white" onClick={()=>query.refetch()} disabled={query.isFetching}><RefreshCw size={15} className={query.isFetching?'animate-spin':''}/><span className="sr-only">Actualizar datos del tablero</span></Button><Button className="bg-white text-slate-900 hover:bg-slate-100" onClick={()=>{setEditing(v=>!v);}}><SlidersHorizontal size={15} className="mr-2"/>{editing?'Terminar de ordenar':'Personalizar'}</Button></div>
    </div>
    <div className="relative grid grid-cols-2 xl:grid-cols-4 gap-3 mt-7">
     {[[data.players.length,'Jugadores en tu alcance'],[data.permissions.matches?data.fixtures.filter(f=>argentinaDay(f.date)===today).length:'—','Partidos registrados hoy'],[data.permissions.calendar?overdue.length:'—','Seguimientos por revisar'],[contracts.length,'Contratos en radar']].map(([value,label])=><div key={label} className="border border-white/10 bg-white/[.04] rounded-2xl px-4 py-3"><p className="text-2xl font-semibold tracking-tight">{value}</p><p className="text-[11px] text-slate-400 mt-1">{label}</p></div>)}
    </div>
   </header>
   <div className="flex flex-wrap items-center justify-between gap-3"><div className="flex gap-2 flex-wrap items-center"><span className="text-xs font-medium text-slate-500">{now.toLocaleDateString('es-AR',{timeZone:'America/Argentina/Buenos_Aires',weekday:'long',day:'numeric',month:'long'})}</span><span className="h-1 w-1 bg-slate-300 rounded-full"/><span className="text-xs text-slate-400">{visible.length} widgets</span></div><div className="flex flex-wrap gap-2 items-center">{data.permissions.statistics&&<><select aria-label="Temporada de Sportmonks" className={selectClass} value={seasonId} onChange={e=>change({season_id:e.target.value})}>{!seasons.length&&<option value="">Sportmonks · Temporada pendiente</option>}{seasons.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select><button className={'text-xs rounded-full border px-3 py-1.5 '+(data.sportmonks.synced_players?'bg-emerald-50 border-emerald-200 text-emerald-800':'bg-amber-50 border-amber-200 text-amber-800')} onClick={()=>setSetup(true)}>Sportmonks · {data.sportmonks.synced_players?'Datos guardados':data.sportmonks.configured?'Sin sincronizar':'Pendiente de conexión'}</button></>}</div></div>
   {message&&<p role="status" className="rounded-xl border bg-white p-3 text-sm text-slate-700">{message}</p>}
   {query.isError&&data&&<p role="alert" className="text-sm text-amber-800 bg-amber-50 rounded-xl p-3">No se pudieron actualizar los datos. Se muestra la última consulta disponible.</p>}
   {editing&&<div className="flex flex-wrap items-center justify-between gap-3 bg-white rounded-2xl p-4 border border-dashed" style={{borderColor:accent}}><p className="text-sm text-slate-600">Arrastrá desde el agarre o usá las flechas. Podés cambiar tamaño, cantidad de filas y visibilidad.</p><Button size="sm" variant="outline" onClick={()=>setCatalog(true)}><Plus size={14} className="mr-1"/>Widgets y preferencias</Button></div>}
   <div className={'grid grid-cols-1 lg:grid-cols-2 2xl:grid-cols-3 items-start '+(prefs.compact?'gap-3':'gap-5')}>
    {visible.map(widget=>{const meta=WIDGET_CATALOG.find(c=>c.id===widget.id),Icon=ICONS[meta.icon];return <section key={widget.id} onDragOver={e=>{if(editing)e.preventDefault();}} onDrop={e=>{if(editing){e.preventDefault();change({widgets:moveWidget(prefs.widgets,e.dataTransfer.getData('text/plain'),widget.id)});}} className={(widget.size==='wide'?'lg:col-span-2 ':'')+'rounded-[22px] border border-slate-200/70 bg-white shadow-[0_3px_20px_rgba(15,23,42,0.025)] overflow-hidden transition-shadow hover:shadow-md'}>
     <div className={'flex items-center justify-between gap-2 '+(prefs.compact?'px-4 pt-4':'px-5 pt-5')}><div className="flex gap-2 items-center"><div className="rounded-lg p-2" style={{color:accent,backgroundColor:accent+'0c'}}><Icon size={16}/></div><h2 className="text-sm font-bold tracking-tight">{meta.title}</h2></div>{editing?<div className="flex gap-1"><button draggable onDragStart={e=>e.dataTransfer.setData('text/plain',widget.id)} aria-label={'Arrastrar '+meta.title} className="p-1 text-slate-400 cursor-grab"><GripVertical size={16}/></button><button disabled={prefs.widgets[0]?.id===widget.id} onClick={()=>shift(widget.id,-1)} aria-label={'Subir '+meta.title} className="p-1 text-slate-400 disabled:opacity-20"><ArrowUp size={15}/></button><button disabled={prefs.widgets.at(-1)?.id===widget.id} onClick={()=>shift(widget.id,1)} aria-label={'Bajar '+meta.title} className="p-1 text-slate-400 disabled:opacity-20"><ArrowDown size={15}/></button><button onClick={()=>toggleWidget(widget.id)} aria-label={'Ocultar '+meta.title} className="p-1 text-slate-400 hover:text-rose-600"><X size={15}/></button></div>:<span className="h-1 w-1 rounded-full bg-slate-200"/>}</div>
     {editing&&<div className="flex gap-2 px-5 pt-3"><select aria-label={'Tamaño de '+meta.title} className={selectClass} value={widget.size} onChange={e=>patchWidget(widget.id,{size:e.target.value})}><option value="normal">Estándar</option><option value="wide">Ampliado</option></select><select aria-label={'Filas de '+meta.title} className={selectClass} value={widget.limit} onChange={e=>patchWidget(widget.id,{limit:Number(e.target.value)})}>{[3,5,8].map(n=><option key={n} value={n}>{n} filas</option>)}</select></div>}
     <div className={prefs.compact?'p-4':'p-5'}>{body(widget)}</div>
    </section>;})}
   </div>
   {!visible.length&&<Empty action={<Button onClick={()=>setCatalog(true)}><Plus size={15} className="mr-2"/>Agregar widgets</Button>}>Tu espacio está listo para que elijas qué querés ver.</Empty>}
   <div className="flex flex-wrap justify-between gap-3 text-[11px] text-slate-400"><span>Última lectura del tablero: {dateLabel(data.generated_at)} · Consulta cada 60 segundos</span><Link to="/agency/operations" className="hover:text-slate-700">Abrir agenda y partidos →</Link></div>
   <button className="inline-flex items-center gap-2 text-sm font-medium text-slate-500" onClick={()=>setCatalog(true)}><LayoutGrid size={16}/>Elegir mis widgets y jugadores</button>
  </div>

  {dirty&&<div className="fixed bottom-4 left-4 lg:left-[272px] right-4 z-30 rounded-2xl bg-slate-950 text-white shadow-xl px-5 py-4 flex flex-wrap items-center justify-between gap-3"><p className="text-sm"><LockKeyhole className="inline mr-2 h-4 w-4 text-emerald-300"/>Cambios en tu vista personal</p><div className="flex gap-2"><Button disabled={saving} variant="ghost" className="text-slate-300 hover:bg-white/10 hover:text-white" onClick={resetDraft}>Descartar</Button><Button disabled={saving} className="text-white" style={{backgroundColor:accent}} onClick={save}>{saving?<Loader2 size={15} className="animate-spin mr-2"/>:<Check size={15} className="mr-2"/>}Guardar mi tablero</Button></div></div>}

  <Dialog open={catalog} onOpenChange={setCatalog}><DialogContent className="max-w-3xl max-h-[85vh] overflow-y-auto"><DialogHeader><DialogTitle>Diseñá tu espacio de trabajo</DialogTitle><DialogDescription>Elegí widgets, colores y jugadores prioritarios. Al guardar, los cambios se aplican únicamente a tu cuenta dentro de Score.</DialogDescription></DialogHeader>
   <div className="flex flex-wrap gap-3 items-center"><span className="text-xs text-slate-500">Acento</span>{Object.entries(ACCENTS).map(([id,color])=><button key={id} aria-label={'Color '+id} aria-pressed={prefs.accent===id} onClick={()=>change({accent:id})} style={{backgroundColor:color}} className={'h-7 w-7 rounded-full border-2 '+(prefs.accent===id?'ring-2 ring-offset-2 ring-slate-300 border-white':'border-transparent')}/>)}<label className="ml-auto text-sm flex items-center gap-2"><input type="checkbox" checked={prefs.compact} onChange={e=>change({compact:e.target.checked})}/>Vista compacta</label></div>
   <div className="grid sm:grid-cols-2 gap-3">{WIDGET_CATALOG.filter(permitted).map(meta=>{const active=prefs.widgets.some(w=>w.id===meta.id),Icon=ICONS[meta.icon];return <button key={meta.id} aria-pressed={active} onClick={()=>toggleWidget(meta.id)} className={'rounded-xl border p-4 text-left flex gap-3 '+(active?'bg-emerald-50/50 border-emerald-200':'bg-white border-slate-200')}><Icon size={19} className="shrink-0 text-slate-500"/><div className="flex-1"><p className="text-sm font-semibold">{meta.title}</p><p className="text-xs text-slate-500 mt-1">{meta.description}</p></div>{active?<Check size={16} className="text-emerald-600"/>:<Plus size={16}/>}</button>;})}</div>
   <h3 className="text-sm font-semibold mt-3">Jugadores prioritarios · Solo para vos</h3><div className="max-h-52 overflow-y-auto grid sm:grid-cols-2 gap-2 border rounded-xl p-3">{data.players.map(p=><label key={p.id} className="flex items-center gap-2 text-sm p-2 rounded-lg hover:bg-slate-50"><input type="checkbox" checked={prefs.favorite_player_ids.includes(p.id)} onChange={()=>toggleFavorite(p.id)}/><span>{p.name}</span></label>)}{!data.players.length&&<p className="text-sm text-slate-500">No hay jugadores disponibles en tu alcance.</p>}</div>
   <Button onClick={()=>{setCatalog(false);setEditing(true);}}>Volver a mi tablero</Button>
  </Dialog>
  <SportmonksSetup key={setup?'open':'closed'} open={setup} onOpenChange={setSetup} orgId={orgId} data={data} onUpdated={refresh}/>
 </div>;
}
